### ISSUE TITLE
How i can support windows or linux?

### ISSUE THREAD

**Issue by andresdev16** [androbwebb/JenniferVirtualAssistant#2]
Hello, I would like how I could do so that the assistant can run on Linux or Windows?

**Comment by androbwebb** [comment]
I think linux should be fine - just need the right python version. As for windows, I'm not too sure, I'm pretty unfamliar with windows. There might be some file paths that need to be updated.

**Comment by andresdev16** [comment]
what version of python is good?

**Comment by androbwebb** [comment]
I just upgraded everything to python3 today. I couldn't figure out which version I originally wrote this using, but it was definitely python2. I tested this using python 3.7.6 today, but it should work with 3.6 and up.

**Comment by andresdev16** [comment]
I'll try. Can i contact you if i found any error in the process?, i'll try run it in windows.

**Comment by androbwebb** [comment]
Sure thing! That would be great
